/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppReceiveRouteImport } from './routes/app.receive'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AuthCreatePinRouteImport } from './routes/auth.create-pin'
import { Route as AuthEnterPinRouteImport } from './routes/auth.enter-pin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRecoveryPhraseRouteImport } from './routes/auth.recovery-phrase'
import { Route as AuthRecoveryPhraseVerifyRouteImport } from './routes/auth.recovery-phrase-verify'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthWelcomeRouteImport } from './routes/auth.welcome'
import { Route as AppPortfolioAssetRouteImport } from './routes/app.portfolio_.$asset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AuthCreatePinRoute = AuthCreatePinRouteImport.update({
  id: '/auth/create-pin',
  path: '/auth/create-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEnterPinRoute = AuthEnterPinRouteImport.update({
  id: '/auth/enter-pin',
  path: '/auth/enter-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryPhraseRoute = AuthRecoveryPhraseRouteImport.update({
  id: '/auth/recovery-phrase',
  path: '/auth/recovery-phrase',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryPhraseVerifyRoute =
  AuthRecoveryPhraseVerifyRouteImport.update({
    id: '/auth/recovery-phrase-verify',
    path: '/auth/recovery-phrase-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/auth/welcome',
  path: '/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPortfolioAssetRoute = AppPortfolioAssetRouteImport.update({
  id: '/portfolio_/$asset',
  path: '/portfolio/$asset',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/create-pin': typeof AuthCreatePinRoute
  '/auth/enter-pin': typeof AuthEnterPinRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery-phrase': typeof AuthRecoveryPhraseRoute
  '/auth/recovery-phrase-verify': typeof AuthRecoveryPhraseVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/portfolio/$asset': typeof AppPortfolioAssetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/create-pin': typeof AuthCreatePinRoute
  '/auth/enter-pin': typeof AuthEnterPinRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery-phrase': typeof AuthRecoveryPhraseRoute
  '/auth/recovery-phrase-verify': typeof AuthRecoveryPhraseVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/app': typeof AppIndexRoute
  '/app/portfolio/$asset': typeof AppPortfolioAssetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/create-pin': typeof AuthCreatePinRoute
  '/auth/enter-pin': typeof AuthEnterPinRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery-phrase': typeof AuthRecoveryPhraseRoute
  '/auth/recovery-phrase-verify': typeof AuthRecoveryPhraseVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/portfolio_/$asset': typeof AppPortfolioAssetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/portfolio'
    | '/app/receive'
    | '/app/settings'
    | '/app/wallet'
    | '/auth/create-pin'
    | '/auth/enter-pin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recovery-phrase'
    | '/auth/recovery-phrase-verify'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/welcome'
    | '/app/'
    | '/app/portfolio/$asset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/activity'
    | '/app/portfolio'
    | '/app/receive'
    | '/app/settings'
    | '/app/wallet'
    | '/auth/create-pin'
    | '/auth/enter-pin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recovery-phrase'
    | '/auth/recovery-phrase-verify'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/welcome'
    | '/app'
    | '/app/portfolio/$asset'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/portfolio'
    | '/app/receive'
    | '/app/settings'
    | '/app/wallet'
    | '/auth/create-pin'
    | '/auth/enter-pin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recovery-phrase'
    | '/auth/recovery-phrase-verify'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/welcome'
    | '/app/'
    | '/app/portfolio_/$asset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCreatePinRoute: typeof AuthCreatePinRoute
  AuthEnterPinRoute: typeof AuthEnterPinRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoveryPhraseRoute: typeof AuthRecoveryPhraseRoute
  AuthRecoveryPhraseVerifyRoute: typeof AuthRecoveryPhraseVerifyRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receive': {
      id: '/app/receive'
      path: '/receive'
      fullPath: '/app/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/create-pin': {
      id: '/auth/create-pin'
      path: '/auth/create-pin'
      fullPath: '/auth/create-pin'
      preLoaderRoute: typeof AuthCreatePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/enter-pin': {
      id: '/auth/enter-pin'
      path: '/auth/enter-pin'
      fullPath: '/auth/enter-pin'
      preLoaderRoute: typeof AuthEnterPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery-phrase': {
      id: '/auth/recovery-phrase'
      path: '/auth/recovery-phrase'
      fullPath: '/auth/recovery-phrase'
      preLoaderRoute: typeof AuthRecoveryPhraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery-phrase-verify': {
      id: '/auth/recovery-phrase-verify'
      path: '/auth/recovery-phrase-verify'
      fullPath: '/auth/recovery-phrase-verify'
      preLoaderRoute: typeof AuthRecoveryPhraseVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/auth/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/portfolio_/$asset': {
      id: '/app/portfolio_/$asset'
      path: '/portfolio/$asset'
      fullPath: '/app/portfolio/$asset'
      preLoaderRoute: typeof AppPortfolioAssetRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPortfolioAssetRoute: typeof AppPortfolioAssetRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppPortfolioAssetRoute: AppPortfolioAssetRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCreatePinRoute: AuthCreatePinRoute,
  AuthEnterPinRoute: AuthEnterPinRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoveryPhraseRoute: AuthRecoveryPhraseRoute,
  AuthRecoveryPhraseVerifyRoute: AuthRecoveryPhraseVerifyRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
